s=set()
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
n=input("Enter the value:")
s.add(int(n))
print(s)